### ISSUE TITLE
System.MissingMethodException: Method not found: 'Void FSharp.Data.FlatFileMeta.FlatRow.SetColumn(!!0, Microsoft.FSharp.Core.FSharpOption`1<System.String>)'

### ISSUE THREAD

**Issue by Thorium** [ekonbenefits/NachaSharp#12]
The same code that used to work (e.g. you can take a one from #4) now fails to generate ACH file for the following error:

```
> testAch();;
System.MissingMethodException: Method not found: 'Void FSharp.Data.FlatFileMeta.FlatRow.SetColumn(!!0, Microsoft.FSharp.Core.FSharpOption`1<System.String>)'.
   at NachaSharp.FileHeaderRecord.set_ImmediateDestination(String value)
   at <StartupCode$NachaSharp>.$FileHeaderRecord.Create@39-10.Invoke(FileHeaderRecord _arg1)
   at FSharp.Data.FlatFileMeta.CreateRowExtension.CreateRowBuilder.Bind[a6,a7](FSharpFunc`2 m, FSharpFunc`2 f)
   at NachaSharp.FileHeaderRecord.Create(String immediateDest, String immediateOrigin, String fileIDModifier, String immediateDestName, String immediateOriginName, String referenceCode, Int32 priorityCode, Int32 blockingFactor)
   at FSI_0003.create_ach_file@71.Invoke(Unit unitVar) in C:\Users\th\AppData\Local\Temp\stdin:line 75
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 510
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 112
--- End of stack trace from previous location ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit() in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 454
   at Microsoft.FSharp.Control.AsyncPrimitives.QueueAsyncAndWaitForResultSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 1139
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 1515
   at <StartupCode$FSI_0004>.$FSI_0004.main@() in C:\Users\th\AppData\Local\Temp\stdin:line 127
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
Stopped due to error

**Comment by Thorium** [comment]
Closing this for now, there might have been something wrong with my FSI.
